config/routes.rb
Rails.application.routes.draw do
  get 'hello/index'
  post 'hello/index' => 'hello#create'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/hello_controller.rb
class HelloController < ApplicationController
  attr_reader :name
  def index
    @name = 'Sisko'
  end

  def create
    @name_array = ['Sisko', 'Kirk', 'Picard']
    name_index = rand(3)
    @name = @name_array[name_index]

    respond_to do |format|
      format.js 
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/hello_helper.rb
module HelloHelper
end

app/views/hello/_hello.html.erb
<p>Hello, <%= name %></p>

app/views/hello/create.js.erb
$('#hello').html("<%= j render 'hello', name: @name %>")

app/views/hello/index.html.erb
<h1>Hello#index</h1>

<%= button_to 'random greeting', hello_index_path, remote: true %>
<div>
  <%= @name %>
</div>
<div id="hello">
  <%= render 'hello', name: @name %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsAjaxSandbox</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>